# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e09d2fc423767f9e4393d6584382f89177c6a078c29767467c94dfe9b980e2445279cc4ff2989d024eca0539b45f2d311d3854721b6b84df9a7559e9dbca89de

test:
  secret_key_base: d67399784b9ed923a2b1c05184c00db8ec34d59c51e8b9197c1e2d693c1a0b82f0e122f7c238c9ab99bd32131d358961cc5b0695406e9c2905708211503f4309

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
